CREATE (cust1:Customer{cin:1,firstName:"Petr",lastName:"Cech"})
CREATE (cust2:Customer{cin:2,firstName:"Dan",lastName:"Petrescu"})
CREATE (cust3:Customer{cin:3,firstName:"Ashley",lastName:"Cole"})
CREATE (cust4:Customer{cin:4,firstName:"John",lastName:"Terry"})
CREATE (cust5:Customer{cin:5,firstName:"Riccardo",lastName:"Carvalho"})
CREATE (cust6:Customer{cin:6,firstName:"Claude",lastName:"Makele"})
CREATE (cust7:Customer{cin:7,firstName:"Arjen",lastName:"Robben"})
CREATE (cust8:Customer{cin:8,firstName:"Frank",lastName:"Lampard"})
CREATE (cust9:Customer{cin:9,firstName:"Didier",lastName:"Drogba"})
CREATE (cust10:Customer{cin:10,firstName:"Gianfranco",lastName:"Zola"})
CREATE (cust11:Customer{cin:11,firstName:"Eden",lastName:"Hazard"})

CREATE (acc4:Product:Account{name:"Savings",balance:10000000})
CREATE (acc6:Product:Account{name:"Current",balance:15000000})
CREATE (acc8:Product:Account{name:"Savings",balance:20000000})

CREATE (cust4)-[:HAS]->(acc4)
CREATE (cust6)-[:HAS]->(acc6)
CREATE (cust8)-[:HAS]->(acc8)

CREATE (merc:Merchant{name:"Claus Mercedes"})
CREATE (starbucks:Merchant{name:"Starbucks"})

CREATE (trans1:Transaction{date:"2018-07-13",amount:150000,description:"Mercedes S Class"})<-[:HAS]-(acc6)
CREATE (trans1)-[:TRANSACTING_MERCHANT]->(merc)
CREATE (trans2:Transaction{date:"2018-06-01",amount:4.5,description:"Flat White"})<-[:HAS]-(acc6)
CREATE (trans2)-[:TRANSACTING_MERCHANT]->(starbucks)
CREATE (trans3:Transaction{date:"2018-06-02",amount:4.5,description:"Flat White"})<-[:HAS]-(acc6)
CREATE (trans3)-[:TRANSACTING_MERCHANT]->(starbucks)
CREATE (trans4:Transaction{date:"2018-06-03",amount:4.5,description:"Flat White"})<-[:HAS]-(acc6)
CREATE (trans4)-[:TRANSACTING_MERCHANT]->(starbucks)
CREATE (trans5:Transaction{date:"2018-06-04",amount:4.5,description:"Flat White"})<-[:HAS]-(acc6)
CREATE (trans5)-[:TRANSACTING_MERCHANT]->(starbucks)
CREATE (trans6:Transaction{date:"2018-06-05",amount:4.5,description:"Flat White"})<-[:HAS]-(acc6)
CREATE (trans6)-[:TRANSACTING_MERCHANT]->(starbucks)
CREATE (trans7:Transaction{date:"2018-06-05",amount:4.5,description:"Flat White"})<-[:HAS]-(acc6)
CREATE (trans7)-[:TRANSACTING_MERCHANT]->(starbucks)
CREATE (trans8:Transaction{date:"2018-06-06",amount:4.5,description:"Flat White"})<-[:HAS]-(acc6)
CREATE (trans8)-[:TRANSACTING_MERCHANT]->(starbucks)